language: android
dist: trusty
android:
  components:
    - build-tools-28.0.3
    - android-28
    - extra-google-m2repository
    - extra-android-m2repository
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
before_script:
  - git clone https://github.com/4ntoine/NotesServerApp.git
  - cd NotesServerApp
  - ./gradlew clean assemble publishToMavenLocal
  - cd ..
script:
  - ./gradlew clean test assemble