language: android
dist: trusty
env:
  global:
    - QEMU_AUDIO_DRV=none
    - ADB_INSTALL_TIMEOUT=5 # minutes
android:
  components:
    - build-tools-28.0.3
    - android-19
    - android-28
    - extra-google-m2repository
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-19
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
before_script:
  - git clone https://github.com/4ntoine/NotesServerApp.git
  - cd NotesServerApp
  - ./gradlew clean assemble publishToMavenLocal
  - cd ..
# - echo no | android create avd --force -n test -t android-19 --abi armeabi-v7a -c 100M
# - emulator -avd test -no-window &
# - android-wait-for-emulator
# - adb shell input keyevent 82 &
script:
  - ./gradlew clean test
  - ./gradlew clean assemble podspec
  - ./gradlew clean app-android:assemble
# commented as it's unreliable on Travis due to "Waited for the root of the view hierarchy to have window focus and not request layout for 10 seconds .." error
# - ./gradlew clean app-android:connectedAndroidTest
  - ./gradlew clean app-javafx:shadowJar