# Either use_frameworks! or use_modular_headers! must be specified.
use_frameworks!

platform :ios, '9.0'

target 'app-ios' do
	pod 'app_ios_lib', :path => '../app-ios-lib'
	# (do not remove commented imports below to import them separately starting kotlin 1.3.70)
    # pod 'app_mvp', :path => '../app-mvp'
    # pod 'app_infra_rest_ktor', :path => '../app-infra-rest-ktor'
end