name: app_flutter
description: Notes client Flutter app

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  http: ^0.12.0
  json_annotation: ^3.0.0
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  test: ^1.6.3
  mockito: ^4.1.1
  build_runner: ^1.0.0
  json_serializable: ^3.2.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
